global:
  # Prometheus will try to pull metrics every 15 seconds from all configured targets (unless overridden per job).
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is 1 minute.

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"] # Prometheus will scrape its own metrics at localhost:9090/metrics.
  - job_name: 'backend-service'
    metrics_path: '/actuator/prometheus' # Spring Boot Actuator endpoint for Prometheus metrics.
    static_configs:
      - targets: [ 'backend-service:8080' ] # Docker service name
        labels:
          application: 'Backend Service' #  Adds a static label application="Backend Service" to all metrics scraped from this target — useful in Grafana or PromQL filters.